pencil <- c("box_1","box_2","box_3","box_4","box_5","box_6","box_7","box_8","box_9","box_10")
 boxes <- c("box_1","box_2","box_3","box_4","box_5","box_6","box_7","box_8","box_9","box_10")
 pencil <- c(9,25,23,12,11,6,7,8,9,10)
 pencil_data <- data.frame(boxes=boxes,pencil=pencil)
 print(pencil_data)
 mean_value <- mean(pencil)
 median_value <-median(pencil)
 mode_value <- as.numeric(names(sort(table(pencil),decreasing = TRUE)[1]))
 cat("mean:",mean_value,"\n")
 cat("median:",median_value,"\n")
 cat("mode:",mode_value,"\n")